### ISSUE TITLE
Future Performance Boosts?

### ISSUE THREAD

**Issue by TheRenegadist** [ata4/angrylion-rdp-plus#100]
I'm curious if it's possible to increase performance for this any further than we already have, I know in r8 we now have 3 options for speed vs. compatibility but I'm curious if you guys can do anything further to improve performance. 

I have a 7700k non-overclocked and with my streaming software active a lot of titles are playable and only suffer from minor frame loss to frame loss akin to an actual N64 but it would be nice to get stable speeds without too much dropping. Other games like Indiana Jones and Rayman 2 suffer from large scale frame drops leading to crackling and slowdowns so I'm hoping that with a future update it will be enough to push these types of games into more playable territory because both are teetering on the edge of being playable as is.

**Comment by theboy181** [comment]
Other developers gave vectorizing a change with the RDP. It would be neat to see optimization included in this build.

**Comment by TheRenegadist** [comment]
> 
> 
> Other developers gave vectorizing a change with the RDP. It would be neat to see optimization included in this build.

Can you explain what that entails?

**Comment by ata4** [comment]
You basically tell the processor to perform single mathematical operations on an entire list of values (vectors) instead of processing each value individually. For example, instead of doing `a + b = c` three times in a loop, the processor can do `[a1, a2, a3] + [b1, b2, b3] = [c1, c2, c3]` with just one instruction.

Right now, this fork just splits up the workload on several cores using worker thread, which increases the overall performance as well. But both multithreading and vectorization can be combined to fully take advantage of modern processors. The tricky part is to do that platform-independently while refactoring undocumented code without regressions that wasn't originally written with parallelization in mind.

**Comment by TheRenegadist** [comment]
How big of a performance boost can this bring and is there an ETA on when it might be added?

**Comment by theboy181** [comment]
iirc the work that was completed showed only minor gains in perspective to the speculation of having it multi threaded. 

You would need to tackle and test several different areas of the code, and the gains would only be seen in a game that used the optimized code.

AKA I think its a lot of work, and you would need a small team.

**Comment by TheRenegadist** [comment]
So you're saying right now it doesn't do much or are you saying if completed it won't do much as in this isn't a medium to major performance booster?

**Comment by theboy181** [comment]
What I’m saying is there is an opportunity, however the major boost is the multi threading. The opts will not stack that well.

**Comment by Jj0YzL5nvJ** [comment]
Alternatively, [GPGPU](https://en.wikipedia.org/wiki/General-purpose_computing_on_graphics_processing_units) implementations could be used... [like this one](https://github.com/moon-raccoon-mods/angrylion-rdp-x), closed to NVIDIA (CUDA) BTW. But that can potentially break more things, who knows.

In any case, the main problem at this time is the RSP bottleneck. Could [parallel-rsp](https://github.com/mupen64plus-ae/parallel-rsp) be the solution?
Better performance than CXD4?, that's for sure... But what new bugs that introduce?, that remains to be seen.

**Comment by theboy181** [comment]
@Jj0YzL5nvJ I was unaware of this project. is there any gains from cuda implementation?

**Comment by Jj0YzL5nvJ** [comment]
In theory, yes. But you would also need an RSP implementation to see the true potential.

**Comment by fallaha56** [comment]
interesting

appreciate this might be something discussed elsewhere before but moving the VI to the GPU / CUDA / OpenCL perhaps an easier first step as the final (performance-heavy) part of the processing chain

that plus the improved RSP of course

**Comment by TheRenegadist** [comment]
Well, looks like there's hope for better performance based on the responses here. I was curious about all of this because if I can run Wii/GCN/PS2 games at 60FPS then I should be able to get good speeds with this granted all 3 emulators are different in their inner mechanisms and plugins.

**Comment by theboy181** [comment]
What is the vulkan version of AL like and is it MT?

**Comment by Jj0YzL5nvJ** [comment]
Performance has increased significantly since [my last benchmark](https://github.com/ata4/angrylion-rdp-plus/issues/87#issuecomment-511206172).

Benchmark 2: https://imgur.com/a/4dxZEaJ

For those interested in compiling [mupen64plus-rsp-parallel](https://github.com/mupen64plus-ae/parallel-rsp).

Example:
```
md build
cd build
export CC=clang-7
export CXX=clang++-7
cmake -DCMAKE_C_FLAGS=-fPIC -DCMAKE_BUILD_TYPE=Release -DPARALLEL_RSP_DEBUG_JIT=OFF ..
```

**Comment by TheRenegadist** [comment]
Speaking of your last benchmark, you mentioned you had to do a custom compile of AL so that it forced it to use more CPU power. I have zero knowledge of compiling, is there any way you could compile the latest with that same change, I'm wondering if forcing it to use most of my CPU would heavily improve the performance I have. 

For example on Indiana Jones/GoldenEye I get slowdown and audio crackling despite my CPU only being used at 32%~ and with a boost of just half or a bit over half of that I should be able to get full speeds. None of my speeds so far have been horrible so that's why I think forcing it to use more of my CPU could help push me just enough to ensure full speeds.

**Comment by Jj0YzL5nvJ** [comment]
> Speaking of your last benchmark, you mentioned you had to do a custom compile of AL so that it forced it to use more CPU power.

I never said that, in fact I proposed the exact antithesis of it. **Wouldn't touch it** (CPU) **with a ten foot pole.**
It's actually a overkill solution. _Take the GPU and turn it into an FPGA_.

While such a solution would be theoretically possible, it would not really help improve emulation and potentially would not be sustainable either.
NVIDIA itself proposes to use programming languages like Pascal to program in CUDA more optimally, since Pascal can generate bytecode in a more natural way than JIT with C / C++.

[Check out another developer's opinion regarding GPGPU.](https://github.com/RPCS3/rpcs3/issues/2765)
_angrylion-rdp-x_ uses CUDA, but I don't have the required hardware nor software to test it. And from my point of view it's an incomplete solution, you need the full RCP (RSP + RDP). But I welcome anyone who wants to come to shut my mouth.

https://youtu.be/143k1fqPukk
https://youtu.be/IEWGTpsFtt8

> For example on Indiana Jones/GoldenEye I get slowdown and audio crackling despite my CPU only being used at 32%~ and with a boost of just half or a bit over half of that I should be able to get full speeds. None of my speeds so far have been horrible so that's why I think forcing it to use more of my CPU could help push me just enough to ensure full speeds.

First of all there are many myths and misconceptions related to multithreading in general. To that we must add the misunderstandings of how such techniques benefit videogames.
All this together with the ignorance of some end-users with the firm belief that "the more the better" and/or "the newer the better". When in reality in many cases "less is more and better".


What am I referring to with all this?

Multithreading needs to be adjusted in some cases, that's why it keeps getting better.
Some CPUs can benefit more than others. Too many multithreading could potentially impair performance in some games by spending more time syncing threads.
Some newer Intel processors don't have hyperthreading and other older processors work better without it... etc.

Many old games and emulators have lousy audio on modern versions of Windows, the audio plugins in both Project64 and mupen64plus are extremely old, a logical conclusion can be drawn from this. Neither of them is probably WASAPI compliant and instead "uses" KMixer/DirectSound indirectly.
For this there are two general solutions, improve DirectSound emulation by installing [DirectX End-User Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=8109) and/or using [DxWrapper](https://github.com/elishacloud/dxwrapper), or bypass [KMixer](https://en.wikipedia.org/wiki/Windows_legacy_audio_components#KMixer) altogether.

**Comment by LegendOfDragoon** [comment]
>For example on Indiana Jones/GoldenEye I get slowdown and audio crackling despite my CPU only being used at 32%~

That sounds very unusual. What are your emulator settings? I don't think i've seen a game use less than 50%.
