### ISSUE TITLE
Turok shadow of oblivion de-sync

### ISSUE THREAD

**Issue by 71knight** [ata4/angrylion-rdp-plus#103]
During the cut-scenes, the speech becomes out of sync with the moving mouth of the NPC's.

**Comment by LegendOfDragoon** [comment]
Does this happen with other video plugins?

**Comment by 71knight** [comment]
I haven't tried other less accurate plugins.  I just care about accuracy.

**Comment by Pixelnarium** [comment]
This happens also on other plugins and can happen on real hardware too but not that delayed.

**Comment by GitMoDu** [comment]
If I remember correctly, that game used some new tech for the "advanced lip-syncing", back in the day.

**Comment by Pixelnarium** [comment]
I recorded the intro from my real N64. I don't have an US N64, only a PAL one, so I use an Everdrive to start the US version of the game (game runs in PAL 60Hz then). You can see the desync at the end of the video.

It could be because of the whole PAL60 and/or Everdrive thing but again that way it is the same on real hardware.

[Link to Video (MEGA)](https://mega.nz/file/djIhlKYA#phYiU2LMId-c2X_P1vAx3wRbM0miGnNZVHOJefqEBI0)
