### ISSUE TITLE
Banjo Kazooie And Tooie don't start

### ISSUE THREAD

**Issue by schubertguilherme** [ata4/angrylion-rdp-plus#118]
![Untitled](https://user-images.githubusercontent.com/36903073/110374221-2f480780-802f-11eb-9e0a-a1e91bacdf5d.png)

Don't start this games, i using last release.

**Comment by Jj0YzL5nvJ** [comment]
Yeah... I can confirm.

<details>
 <summary>It works with ui-console...</summary>

<img src="https://i.imgur.com/SvCAM2p.png" alt="" class="">

</details>

**Comment by schubertguilherme** [comment]
Mupen is working... but Project 64 freeze.

**Comment by Jj0YzL5nvJ** [comment]
You can try to trace the issue using the [WIPs](https://github.com/ata4/angrylion-rdp-plus/issues/29). I only have access to Windows machines at work and right now I don't really have any spare time.

**Comment by Alexn64gamer0712** [comment]
Is the issue with Rare games being worked for next release? (there are some games affected, Banjo Kazooie and Tooie, Conker, DK64)

**Comment by ata4** [comment]
This has been caused by commit 87790733439d83c2a13ac5c0288e47761a680c85 by a pull request, which IIRC fixes timing issues in other games in Project64 3.X but unfortunately completely breaks several Rare games. The last time I've looked into this it was deemed to be an emulator issue that will be fixed in the future. But I see that it's still present, so I don't really have much hopes that it will be fixed on the emulator's side. 2.4 still works fine, even without clearing the FREEZE bit.

Undoing that commit allows the games to run with graphical issues, such as repeated/out of order frames, but at least they run. Since I have currently no better options for 3.X, I'll probably have to add a config option to re-enable that behavior until a better fix has been found.

**Comment by Jj0YzL5nvJ** [comment]
Said games work fine with CXD4 RSP and ParaLLEl RSP if "Graphics HLE" is checked... I see a pattern there...

@Alexn64gamer0712, try with [angrylion-plus_v1.6-24-dirty](https://github.com/ata4/angrylion-rdp-plus/files/8953195/angrylion-plus_v1.6-24-dirty.zip) without 87790733439d83c2a13ac5c0288e47761a680c85 if that make you happy... #142
