### ISSUE TITLE
Offtopic but.

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [ata4/angrylion-rdp-plus#14]
will you keep on working on "disunity"

**Comment by ata4** [comment]
Sorry, but I don't plan to work on it right now or in the near future. Working with binary Unity files becomes more and more complicated with every new major release and what started as a simple experiment years ago turned into a total mess. I should probably disabled the issues page there all together, because there's no hope I'm ever going to fix all the bugs that have accumulated.
