### ISSUE TITLE
screenshots different sizes depending on ViMode

### ISSUE THREAD

**Issue by loganmc10** [ata4/angrylion-rdp-plus#46]
With ViMode set to 0 (filtered), the resolution of the screenshot is the size of the window.

With ViMode set to 1 (unfiltered), the resolution of the screenshot is the resolution of the game.

Tested with mupen64plus, latest master

**Comment by ata4** [comment]
Filtered screenshots should have a size of 640x480, regardless of the window size. The resolution of unfiltered screenshots depends on the DP resolution, which should be around 320x237 most of the time. So I would say it's working as intended: screenshots are created with the actual resolution, rather than the upscaled window resolution, which makes more sense for software rendering.

**Comment by loganmc10** [comment]
Ah ok got it
