### ISSUE TITLE
disunity 'types.dat' file

### ISSUE THREAD

**Issue by ye1088** [ata4/angrylion-rdp-plus#50]
Can you tell me how you can say how the'types.dat'file is generated?

期待您的回答,<img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1514707870101&di=39e34f8d2d2d0374830cff830413df1c&imgtype=0&src=http%3A%2F%2Fpic123.nipic.com%2Ffile%2F20170307%2F24790314_202246895000_2.jpg"></img>

**Comment by ata4** [comment]
Well, that's very off-topic here. But since the issues are closed for disunity, I'll make an exception.

That database file is filled with runtime type information extracted from Unity asset files that contain such information to read those that don't have it. I've used a collection of Unity web games to cover most of it between 2.x and 5.x, but it's really a pain to keep it updated.

**Comment by ye1088** [comment]
Thank you very much. Although 'disunity' hasn't been updated, I think it's the best one to use. Thank you very much. I'll find other ways to continue to extract unity game resources.

Thanks!~
